/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import '@/test/setup-dom.js';
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import * as echarts from 'echarts';
import type { ChartSelectEvent } from './useEChart.js';
import { selectionFromEChartEvent } from './useEChart.js';

describe('chart click replacement selection (#4832)', () => {
  it('replaces A with B from the events generated by a real ECharts click path', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const emitted: ChartSelectEvent[] = [];
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      xAxis: { type: 'category', data: ['A', 'B'] },
      yAxis: { type: 'value' },
      series: [{ type: 'bar', selectedMode: 'multiple', data: [1, 2] }],
    });
    chart.on('selectchanged', (rawEvent) => {
      const event = rawEvent as Parameters<typeof selectionFromEChartEvent>[0];
      rawEvents.push(event);
      emitted.push(selectionFromEChartEvent(event));
    });

    try {
      const internals = chart as unknown as {
        getModel: () => {
          getSeriesByIndex: (index: number) => {
            getData: () => { getItemGraphicEl: (index: number) => object | undefined };
          };
        };
      };
      const series = internals.getModel().getSeriesByIndex(0);
      const first = series.getData().getItemGraphicEl(0);
      const second = series.getData().getItemGraphicEl(1);
      assert.ok(first);
      assert.ok(second);
      chart.getZr().trigger('click', { target: first, topTarget: first });
      chart.getZr().trigger('click', { target: second, topTarget: second });

      assert.deepEqual(emitted, [
        { items: [{ seriesIndex: 0, dataIndex: 0 }] },
        { items: [{ seriesIndex: 0, dataIndex: 1 }] },
      ]);
      assert.deepEqual(rawEvents[1]?.selected, [{ seriesIndex: 0, dataIndex: [0, 1] }]);
      assert.equal(rawEvents[1]?.fromActionPayload?.dataIndexInside, 1);
      assert.equal(rawEvents[1]?.fromActionPayload?.dataIndex, undefined);
    } finally {
      chart.dispose();
    }
  });

  it('maps a real legend-filtered internal click index back to the raw bucket (#4832)', () => {
    const host = document.createElement('div');
    const chart = echarts.init(host, undefined, { renderer: 'svg', width: 400, height: 300 });
    const emitted: ChartSelectEvent[] = [];
    const rawEvents: Array<Parameters<typeof selectionFromEChartEvent>[0]> = [];
    chart.setOption({
      animation: false,
      legend: { data: ['A', 'B'], selected: { A: false, B: true } },
      series: [{
        type: 'pie',
        selectedMode: 'multiple',
        data: [{ name: 'A', value: 1 }, { name: 'B', value: 2 }],
      }],
    });
    const internals = chart as unknown as {
      getModel: () => {
        getSeriesByIndex: (index: number) => {
          getData: () => {
            getItemGraphicEl: (index: number) => object | undefined;
            getRawIndex: (index: number) => number;
          };
        };
      };
    };
    const rawIndex = (seriesIndex: number, dataIndexInside: number): number => (
      internals.getModel().getSeriesByIndex(seriesIndex).getData().getRawIndex(dataIndexInside)
    );
    chart.on('selectchanged', (rawEvent) => {
      const event = rawEvent as Parameters<typeof selectionFromEChartEvent>[0];
      rawEvents.push(event);
      emitted.push(selectionFromEChartEvent(event, rawIndex));
    });

    try {
      const series = internals.getModel().getSeriesByIndex(0);
      const visibleB = series.getData().getItemGraphicEl(0);
      assert.ok(visibleB, 'legend filtering leaves B at internal index zero');
      assert.equal(series.getData().getRawIndex(0), 1);
      chart.getZr().trigger('click', { target: visibleB, topTarget: visibleB });

      assert.equal(rawEvents[0]?.fromActionPayload?.dataIndexInside, 0);
      assert.deepEqual(rawEvents[0]?.selected, [{ seriesIndex: 0, dataIndex: [1] }]);
      assert.deepEqual(emitted, [{ items: [{ seriesIndex: 0, dataIndex: 1 }] }]);
    } finally {
      chart.dispose();
    }
  });

  it('clears selection when the current bucket is unselected', () => {
    assert.deepEqual(selectionFromEChartEvent({
      fromAction: 'toggleSelected',
      fromActionPayload: { seriesIndex: 0, dataIndex: 1 },
      selected: [],
    }), { items: [] });
  });

  it('retains cumulative fallback semantics for non-click actions without a payload', () => {
    assert.deepEqual(selectionFromEChartEvent({
      selected: [
        { seriesIndex: 0, dataIndex: [2] },
        { seriesIndex: 1, dataIndex: [3] },
      ],
    }), { items: [
      { seriesIndex: 0, dataIndex: 2 },
      { seriesIndex: 1, dataIndex: 3 },
    ] });
  });
});
