/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Demo-kit loaders. The kit (a purpose-built sample project plus fixtures
 * for the feature tours) is generated by `tools/demo-kit/generate.mts` and
 * committed under `public/samples/`; tours must never regenerate it at
 * runtime. Loading rides the existing `ifc-lite:load-file` bus event whose
 * listener routes into the normal loadFile pipeline (so `store.source`
 * bytes are retained for IDS et al).
 */

import { EVENT_LOAD_FILE } from './events';

export const DEMO_KIT_PATHS = {
  base: '/samples/demo-project.ifc',
  revB: '/samples/demo-project-rev-b.ifc',
  ids: '/samples/demo-project.ids',
  lenses: '/samples/demo-project.lenses.json',
  manifest: '/samples/demo-kit.json',
} as const;

async function fetchAsFile(path: string, name: string): Promise<File> {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`demo kit fetch failed: ${res.status} ${path}`);
  const blob = await res.blob();
  return new File([blob], name, { type: 'application/x-step' });
}

/**
 * Load the demo project into the viewer, replacing the current model (the
 * `ifc-lite:load-file` listener routes to `loadFile`). The caller observes
 * completion through the store (`models.size > 0 && !loading &&
 * !geometryStreamingActive`) - same contract as a user-driven open.
 */
export async function loadDemoProject(): Promise<void> {
  const file = await fetchAsFile(DEMO_KIT_PATHS.base, 'demo-project.ifc');
  // detail IS the File - the MainToolbar listener reads e.detail directly.
  window.dispatchEvent(new CustomEvent(EVENT_LOAD_FILE, { detail: file }));
}
