/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Provider guidance for reviewed native authoring (`model-authoring.ts`):
 * the exact contract, kept short so it fits beside evidence. Sent with the
 * `model.changes` guidance (`MODEL_CHANGE_OUTPUT_GUIDANCE`), so every
 * non-flow conversation can propose either kind.
 */

import { PROFILE_FIELDS, PROFILE_KINDS } from '@/lib/profile-section/profile-kinds';

const sectionDimensions = PROFILE_KINDS.map((type) => `${type} {${PROFILE_FIELDS[type].map((field) => field.name).join(',')}}`).join('; ');

export const MODEL_AUTHORING_OUTPUT_GUIDANCE =
  'When asked to create, replace, copy, array, delete, move, turn, trim, extend, type, join or place elements, return only JSON {"version":1,"kind":"model.authoring",'
  + '"title":"Short title","rationale":"Why","units":"mm","frame":"storey-local","operations":[...]}. "units" is "m" or "mm" and applies to command lengths (nativeTrimExtendExpected is a verbatim mixed-unit source snapshot); '
  + 'coordinates are storey-local [x,y,z], Z up; angles are degrees counter-clockwise from above. Existing elements are '
  + '{"globalId","ifcClass","name"} exactly as in the evidence; elements created earlier in the batch are {"ref":"wall-1"}. Ops: '
  + 'element.replace {ref,target (existing),storey:{globalId},ifcClass,name,params,expected:nativeReplacementExpected}; copy the COMPLETE current nativeReplacementExpected unchanged, which pins native references and placement fields in native units. Only destination params use declared m/mm lengths. The same ten source/destination families are IfcWall|IfcColumn|IfcSlab|IfcBeam|IfcSpace|IfcRoof|IfcPlate|IfcMember|IfcStair|IfcRailing. Ordinary destination params use element.create, Stair/Railing use their existing canonical params. Hosted-opening and non-stair aggregate sources refuse; Stair removal requires its native unique single-flight ownership. Replacement creates a new product record; type/material/properties are not transferred and shared old geometry/style leaves are retained. Preview shows destination only, with the existing native profile/Stair limitations; missing source/current snapshot is unavailable and cannot be guessed. '
  + 'element.create {ref, ifcClass: IfcWall|IfcSlab|IfcRoof|IfcPlate|IfcColumn|IfcBeam|IfcMember|IfcSpace, storey:{globalId}, name, params}: '
  + 'walls {start,end,thickness,height}, beams/members {start,end,width,height}, columns {position (base centre),width,depth,height}, '
  + 'slabs/roofs/plates {position (corner),width,depth,thickness}, spaces {position,width,depth,height}; '
  + 'slabs/roofs/plates/spaces also accept {Profile:"polygon", OuterCurve:[[x,y],...], position:[x,y,z] (optional, default zero), thickness or height}; 3–256 vertices and a bounded total outline work budget. '
  + 'beams/members may replace width/height with Profile; columns may replace width/depth with Profile. Profile is the native PascalCase {Type:Rectangle|I|L|T|U|C|Circle|RectangleHollow|CircleHollow, exact native dimension attributes}; every profile dimension uses the batch units. Do not combine Profile with rectangular section dimensions. '
  + `Required Profile dimensions: ${sectionDimensions}. Optional native fillet-radius attributes may be supplied when supported by that section; they use the same units. `
  + 'Positive fillet radii are written accurately but the preview uses the native sharp-corner approximation; review discloses this. '
  + 'Native builder acceptance is not a polygon topology/engineering validity verdict; use simple valid footprints. '
  + 'curtainWall.create {ref,storey,params}: canonical Start/End:[x,y,z] at the same base elevation, Height, optional UGrid/VGrid as integer bay counts or strictly increasing interior length offsets, MullionProfile/TransomProfile as native Profile sections, PanelThickness, EdgeMembers, PredefinedType:USERDEFINED|NOTDEFINED, Name/Description/ObjectType/Tag/GlobalId. All lengths and profile dimensions use batch units; bay counts do not scale. Native layout creates one IfcCurtainWall aggregating every IfcMember and IfcPlate, with explicit review counts. At most 1500 panels per wall and 5000 native parts per batch; no truncation. Preview reuses the native command for matching rectangular sections and default 0.024 m panels; other supplied native details, unreadable source frames or live-edited storey elevation have no preview; native Apply remains authoritative. No inferred curved curtain systems or engineering checks. '
  + 'stair.create {ref,storey,params}: canonical Position:[x,y,z], NumberOfRisers, RiserHeight, TreadLength, Width, optional WaistThickness and Direction (radians, never scaled), Name/Description/ObjectType/Tag/GlobalId/FlightGlobalId/PredefinedType. Creates one IfcStair and its IfcStairFlight. '
  + 'railing.create {ref,storey,params}: canonical Path:[[x,y,z],...], Height, optional RailDiameter/PostDiameter/PostSpacing, Name/Description/ObjectType/Tag/GlobalId/PredefinedType. Explicit straight/sloped polyline only. The whole batch is bounded to 5000 native stair steps/railing posts. All length fields use batch units. '
  + 'grid.create {ref,storey:{globalId,modelId},params:{Position:[x,y,z],Direction:radians,UAxes:[{Tag,Start:[x,y],End:[x,y]}],VAxes:[...],WAxes?:[...],Name?,Description?,ObjectType?,PredefinedType?}}: explicit straight axes, at most200 created axes across the batch, unique tags, no inferred tool settings. Position/endpoints use batch length units. '
  + 'column.createOnGrid {ref,storey:{globalId,modelId},params:{Position,Height,Width,Depth,Name?,RefDirection?} or {Position,Height,Profile,Name?,RefDirection?},grid:{target:{globalId,modelId,ifcClass:IfcGrid,name},expected:nativeGrid.expected,IntersectingAxes:[actualAxisExpressId,actualAxisExpressId]} or grid:{ref:earlierGridCreateRef,IntersectingAxes:[uniqueAxisTag,uniqueAxisTag]}}. Expected grid axes and frame retain native SI metres and model-local ids verbatim. Axes have no GlobalId. Do not infer unavailable grid population or dimensions. Position must match the actual native crossing; grid columns preserve IfcGridPlacement/IfcVirtualGridIntersection. Selective approval requires the earlier grid. '
  + 'stair.resize {target,expected:nativeStairExpected,size:{Width?,RiserHeight?,TreadLength?,WaistThickness?}}: expected is the complete native snapshot, verbatim (native IDs, count and metre lengths); convert only the new size lengths to batch units. Never invent unavailable expected data. NumberOfRisers is not edited in place. '
  + 'stair.delete {target} removes a uniquely owned single-flight assembly; railing.delete {target} removes one native railing. stair.replace/railing.replace {target,ref,storey,params} rebuild only a stair/railing as a new product record, with fresh GlobalId by default or explicitly supplied unique GlobalId (and FlightGlobalId for stairs), retaining native ownership/host refusals. Creation refs support later type/material/copy operations. '
  + 'Stair/railing command previews use solid steps (omit stair waist) and square rail/post sections. Custom diameters/vertical rail segments or existing stair edit/removal bodies can have no preview; review discloses limits. No inferred landings, multi-flight stairs, curved runs or railing in-place dimension editor. '
  + 'element.delete {target}; element.move {target, delta:[dx,dy]}; element.rotate {target, angleDeg, pivot?:[x,y], expected?:nativePlacement}; explicit pivot requires the complete nativePlacement expected pin. Pivot lengths use batch units, nativePlacement stays verbatim SI/native IDs. Without pivot the existing native origin rotation is unchanged. element.align {reference:target,targets:[target,...],mode:left|centre|right|top|middle|bottom,expected:{reference:nativePlacement,targets:[nativePlacement,...]}}. Copy every expected pin from current selected or attached evidence; unavailable is unknown. Align requires explicit native geometry preparation in review; boxes are never supplied or guessed in the proposal. Preview shows native bounds only. '
  + 'element.trimExtend {target, mode:trim|extend, expected: nativeTrimExtendExpected from selected-element evidence, click:[x,y], boundary:{line:{a:[x,y],b:[x,y],tMin,tMax,reach}} or {wall:target or earlier ref, expected:that existing wall nativeTrimExtendExpected.wall}}. Targets are existing walls/beams/members, joined walls and sloped supported native sections included. Copy the entire expected native snapshot verbatim; never convert its file coordinates, metre values or internal IDs. Click/line endpoints/reach use declared units; tMin/tMax are finite dimensionless bounds. Ask for unavailable expected geometry or boundary data. Targets and existing wall boundaries require native parent plan coordinates matching the storey; nested translated/turned plan frames refuse rather than reinterpreting clicks. Native fit/shared-geometry/host checks decide; review shows planned end/length/join and outer-body-only or unavailable ghosts. '
  + 'element.resize {target, expected, size}: existing targets only; expected is the full current native dimensions: {kind:"wall",height,thickness}, {kind:"slab",thickness}, or {kind:"linear",length,width,cross,profiled:boolean}. size repeats kind and supplies one or more changed dimensions; linear length may state fixed:"start"|"end". Non-rectangular sections cannot change width/cross through resize. '
  + 'element.profile {target, expected:current Profile, Profile:new Profile}: existing centred beam/column/member extrusion sections only, with the same exact native fields and declared units as creation. Never invent the expected current dimensions/section; ask if unavailable. '
  + 'Selected evidence and explicit attached selections may supply nativeEdit: units:"m", dimensionsStatus/dimensions, profileStatus/Profile. Use available full dimensions or Profile as expected; unavailable is unknown, not zero. These SI snapshots are independent of displayed Qto units and do not grant edit permission or engineering suitability. Convert every expected/new length if choosing batch units:"mm". '
  + 'Resize uses the native hosted-fit/ownership checks; wall/slab thickness also updates only that occurrence\'s material layers. Review states unavailable geometry previews, omitted fillets and outer-body-only previews. '
  + 'element.reassignStorey {target,sourceStorey,destinationStorey,expected}: existing same-model product and storeys only; declare modelId on all three targets; target.name is an empty string when absent, while expected attributes retain exact native null or empty Name. Join every expectedJsonParts string of the matching nativeStoreyReassignments entry, parse that JSON and copy the complete result as expected unchanged in native units (including in mm batches). Preserve Root identity and world placement; complete hosted opening/filling and aggregate/nested dependencies travel together. Missing/ambiguous ownership, native grids, grid-based or unsupported/shared/cyclic placements or stale pins refuse. Review lists dependency count and both storeys; no displaced geometry ghost because world placement stays fixed. Rich evidence is bounded to models with at most20 storeys; missing/projected pins are unavailable, never guessed. '
  + 'element.split {target, expected, cut}: existing native wall, straight beam/column/member, or plan slab/roof/plate/space only. expected is the complete canonical native split snapshot {ok:true,kind,chain,placement:{parent,frame:{o,x,y,z}},storeyId}; never guess missing provenance, dimensions or frame. Only dimensional chain/Profile values and frame.o use batch units; IDs, direction vectors and frame axes keep their native values. cut is {kind:wall|linear,distance} from native axis start, or {kind:slab,a:[x,y],b:[x,y]}. Distances/coordinates use batch units. One row per distinct existing target, bounded explicit batches; the larger piece keeps identity and one new native identity is created. Review discloses cut-marker-only or unavailable preview and native opening assignments/refusals; it does not verify structural engineering intent. '
  + 'element.copy {target (existing or earlier ref), ref, offset:[dx,dy,dz], angleDeg? with pivot:[x,y], storey?:{globalId}, from?:[x,y]}; '
  + 'element.array {target, refs (one per new copy), mode:linear|polar, count (2..201 including original), anchor:[x,y], storey?, from?}; '
  + 'linear requires cursor:[x,y], distance? (spacing, or total span with fit:true), fit?; polar takes angleDeg (default360, full turns omit coincident copy). '
  + 'At most200 new copy roots per batch; native host/assembly dependents travel with each root. Copy an existing source before editing it in the same batch. '
  + 'Copy refs support later copies, type/material assignments, and hosted/join targets when their source is a wall. '
  + 'type.detach {target (existing occurrence), expected:{GlobalId,Name} from nativeType.expected of its current type}; this removes only its type relationship, with no predicted geometry preview. '
  + 'type.assign {target, expected: current type name or null, type:{globalId,name} or {create:{ifcClass,name}}}; '
  + 'material.layers {target (existing wall/slab/roof/plate), scope:element|type, expected:full nativeLayers.expected, MaterialLayers:[{LayerThickness,Material:null|{modelId,expressId,Name}|{create:{Name}}}]}; selected evidence and explicit attachments supply nativeLayers in SI metres. Preserve every expected field and convert all expected/proposed thicknesses and wall dimensions when choosing mm. Only available complete snapshots authorize an edit; unknown or truncated counts do not. Type scope needs full typeLayers plus current type and peer identities, including own occurrence overrides. IfcMaterial is non-root: use source-owned expressId and exact current Name, never invent a material GlobalId. At most32 layers, positive proposed thicknesses and total<=5m. Occurrence walls resize their native body to the layer total, retaining native wall-layout/host refusals; type and slab/roof/plate assignment does not resize occurrence geometry. This is not engineering validation; never invent materials/thicknesses or edit unassigned defaults. '
  + 'material.assign {target, expected, material:{name, create}}; walls.join {walls:[a,b]}; '
  + 'Bare slab openings use hosted.create {kind:opening, host (IfcSlab or a preceding slab ref), params:{Position:[x,y],Width,Depth,CutDepth?}, expected}. Position is host-local XY; dimensions use declared batch units. For existing hosts copy the complete nativeSlabOpeningExpected snapshot (units m) and keep the batch in m; unavailable snapshots cannot be inferred. Earlier slab refs omit expected and use the current native draft. Default CutDepth is readable native slab thickness plus 0.1 m. Slab footprint fit/overlap is not checked; only native cutter bounds on supported upright storey frames, not boolean results; unsupported frames have no slab cut geometry preview. Slab doors/windows are unsupported. '
  + 'For wall hosts: hosted.create {kind: door|window|opening, host (a wall), offset (along the wall from its start to the centre), sill, width, height}. '
  + 'hosted.edit {target (existing door/window/opening), expected:{hostId,openingId,fillingId (null for bare openings),locationPointId,location:[x,y,z],offset,sill,size:{OverallWidth,OverallHeight} or null}, edit:{Offset?,Sill?,OverallWidth?,OverallHeight?}}. '
  + 'State the complete current canonical native binding, position and available size; ids are model-local EXPRESS ids, all location/position/dimension values use declared units. Do not guess missing state. At least one edit field is required. Movement supports bare openings; sizing requires the native door/window filling geometry. Wall hosts only, and native fit/overlap/layout/schema rules remain authoritative. Preview shows post-edit opening bounds, not the filling solid or detailed cut mesh, and reports unavailable geometry before Apply; prior geometry operations in the same model make this single-source hosted preview unavailable. '
  + 'Omit "expected" for elements created in the batch. Never invent dimensions, storeys or GlobalIds the user or evidence did not give; '
  + 'ask instead. The user reviews and previews every operation before anything is applied.';
