#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * World Gym procedural building generator (M2 midterm, B1.2).
 *
 * `generateModel(seed, familyName)` is the single source of truth: given a
 * seed, it deterministically picks a family (unless pinned), draws a
 * parameter set, and authors the building through the exact same
 * @ifc-lite/create code paths the CLI's `ifc-lite create` command uses -
 * metres, identity placement, one IfcCreator instance, one toIfc() call.
 *
 * Determinism: wrapped in withDeterministicRuntime() (lib/deterministic-runtime.mjs)
 * so the two wall-clock/CSPRNG leaks in IfcCreator (GlobalIds via
 * crypto.randomUUID, header/owner-history timestamps via Date.now) are
 * pinned to the seed instead. Same seed in -> byte-identical IFC file out,
 * on this machine or any other.
 *
 * CLI usage:
 *   node generator.mjs --seed 42 [--family frame|office|auto] --out model.ifc [--json]
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { IfcCreator } from '../../packages/create/dist/index.js';
import { withDeterministicRuntime } from './lib/deterministic-runtime.mjs';
import { Rng } from './lib/rng.mjs';
import {
  drawDefectPlan, applyBuildDefects, applyTextDefects, expectationsFromRecords,
} from './lib/corruption.mjs';
import * as frame from './families/frame.mjs';
import * as office from './families/office.mjs';

export const FAMILIES = { frame, office };
export const FAMILY_NAMES = Object.keys(FAMILIES);

/**
 * Generate one model for `seed`. Pure function of (seed, familyName,
 * corruption options) modulo the deterministic-runtime shim - no other
 * inputs.
 *
 * Corruption (adversarial / negative-label mode): `opts.corruptRate` in
 * [0, 1] makes a per-seed Bernoulli draw on the independent `{seed}:corrupt`
 * RNG stream; `opts.forceCorrupt` (true/false) overrides the draw. A
 * corrupted model carries known-by-construction defects (see
 * lib/corruption.mjs) recorded in `model.defects` (what was planted) and
 * `model.expected` (what a correct checker must observe) - ground truth
 * that never depends on the labeler, so the labeler can be validated
 * against it. With corruptRate=0 (the default) output is byte-identical to
 * the v1 generator for every seed.
 *
 * @param {number|string} seed
 * @param {'frame'|'office'|'auto'} familyName
 * @param {{ corruptRate?: number, forceCorrupt?: boolean }} opts
 * @returns {{ seed, family, params, content, entities, stats, labels, corrupted, defects, expected }}
 */
export function generateModel(seed, familyName = 'auto', opts = {}) {
  const { corruptRate = 0, forceCorrupt } = opts;
  const pickRng = new Rng(`${seed}:family`);
  const resolvedFamily = familyName === 'auto' ? pickRng.pick(FAMILY_NAMES) : familyName;
  const family = FAMILIES[resolvedFamily];
  if (!family) {
    throw new Error(`Unknown family "${familyName}". Known: ${FAMILY_NAMES.join(', ')}, auto`);
  }

  const paramRng = new Rng(`${seed}:params:${resolvedFamily}`);
  const params = family.paramSpace(paramRng);

  const corruptRng = new Rng(`${seed}:corrupt`);
  // Always burn the Bernoulli roll before drawing the plan, so a model
  // corrupted via --corrupt-rate is byte-identical to the same seed forced
  // with forceCorrupt: true (the plan starts at the same stream offset
  // either way) - the reward channels' determinism re-proof depends on it.
  const roll = corruptRng.float();
  const corrupted = forceCorrupt ?? (corruptRate > 0 && roll < corruptRate);
  const plan = corrupted ? drawDefectPlan(corruptRng) : [];

  const model = withDeterministicRuntime(seed, () => {
    const creator = new IfcCreator({
      Name: `WorldGym ${resolvedFamily} seed=${seed}`,
      Description: 'Generated by tools/world-gym (M2 midterm pilot)',
      Schema: 'IFC4',
    });
    const labels = family.build(creator, params);
    const firstStoreyId = labels.firstStoreyId;
    delete labels.firstStoreyId;
    const buildRecords = corrupted
      ? applyBuildDefects(creator, firstStoreyId, labels.footprint, plan)
      : [];
    const result = creator.toIfc();
    return {
      seed,
      family: resolvedFamily,
      params,
      content: result.content,
      entities: result.entities,
      stats: result.stats,
      labels,
      buildRecords,
    };
  });

  let records = model.buildRecords;
  delete model.buildRecords;
  if (corrupted) {
    const textResult = applyTextDefects(model.content, plan);
    model.content = textResult.content;
    records = [...records, ...textResult.records];
    // Text surgery may add/remove whole STEP lines; refresh the stats the
    // label reports so they describe the bytes actually written to disk.
    model.stats = {
      ...model.stats,
      entityCount: (model.content.match(/^#\d+=/gm) ?? []).length,
      fileSize: model.content.length,
    };
  }

  model.corrupted = corrupted;
  model.defects = records;
  model.expected = expectationsFromRecords(records);
  return model;
}

// ============================================================================
// CLI entry point
// ============================================================================

async function main() {
  const args = process.argv.slice(2);
  const getFlag = (name) => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const hasFlag = (name) => args.includes(name);

  const seedRaw = getFlag('--seed');
  if (seedRaw === undefined) {
    process.stderr.write('Usage: node generator.mjs --seed <n> [--family frame|office|auto] [--corrupt | --corrupt-rate 0.3] --out <file.ifc> [--json]\n');
    process.exit(1);
  }
  const seed = Number.isFinite(Number(seedRaw)) ? Number(seedRaw) : seedRaw;
  const family = getFlag('--family') ?? 'auto';
  const outPath = getFlag('--out');
  const jsonOutput = hasFlag('--json');
  const corruptRate = Number(getFlag('--corrupt-rate') ?? 0);
  const forceCorrupt = hasFlag('--corrupt') ? true : undefined;

  const model = generateModel(seed, family, { corruptRate, forceCorrupt });

  if (outPath) {
    await writeFile(outPath, model.content, 'utf-8');
  } else if (!jsonOutput) {
    process.stdout.write(model.content);
  }

  if (jsonOutput) {
    process.stdout.write(`${JSON.stringify({
      seed: model.seed,
      family: model.family,
      params: model.params,
      entityCount: model.stats.entityCount,
      fileSize: model.stats.fileSize,
      labels: model.labels,
      corrupted: model.corrupted,
      defects: model.defects,
      expected: model.expected,
      file: outPath ?? null,
    })}\n`);
  } else if (outPath) {
    process.stderr.write(`${model.family} seed=${model.seed}: ${model.stats.entityCount} entities, ${model.stats.fileSize} bytes -> ${outPath}\n`);
  }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    process.stderr.write(`${err.stack ?? err.message}\n`);
    process.exit(1);
  });
}
