#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * World Gym procedural building generator (M2 midterm, B1.2).
 *
 * `generateModel(seed, familyName)` is the single source of truth: given a
 * seed, it deterministically picks a family (unless pinned), draws a
 * parameter set, and authors the building through the exact same
 * @ifc-lite/create code paths the CLI's `ifc-lite create` command uses —
 * metres, identity placement, one IfcCreator instance, one toIfc() call.
 *
 * Determinism: wrapped in withDeterministicRuntime() (lib/deterministic-runtime.mjs)
 * so the two wall-clock/CSPRNG leaks in IfcCreator (GlobalIds via
 * crypto.randomUUID, header/owner-history timestamps via Date.now) are
 * pinned to the seed instead. Same seed in -> byte-identical IFC file out,
 * on this machine or any other.
 *
 * CLI usage:
 *   node generator.mjs --seed 42 [--family frame|office|auto] --out model.ifc [--json]
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { IfcCreator } from '../../packages/create/dist/index.js';
import { withDeterministicRuntime } from './lib/deterministic-runtime.mjs';
import { Rng } from './lib/rng.mjs';
import * as frame from './families/frame.mjs';
import * as office from './families/office.mjs';

export const FAMILIES = { frame, office };
export const FAMILY_NAMES = Object.keys(FAMILIES);

/**
 * Generate one model for `seed`. Pure function of (seed, familyName) modulo
 * the deterministic-runtime shim — no other inputs.
 *
 * @param {number|string} seed
 * @param {'frame'|'office'|'auto'} familyName
 * @returns {{ seed, family: string, params: object, content: string, entities: Array, stats: object, labels: object }}
 */
export function generateModel(seed, familyName = 'auto') {
  const pickRng = new Rng(`${seed}:family`);
  const resolvedFamily = familyName === 'auto' ? pickRng.pick(FAMILY_NAMES) : familyName;
  const family = FAMILIES[resolvedFamily];
  if (!family) {
    throw new Error(`Unknown family "${familyName}". Known: ${FAMILY_NAMES.join(', ')}, auto`);
  }

  const paramRng = new Rng(`${seed}:params:${resolvedFamily}`);
  const params = family.paramSpace(paramRng);

  return withDeterministicRuntime(seed, () => {
    const creator = new IfcCreator({
      Name: `WorldGym ${resolvedFamily} seed=${seed}`,
      Description: 'Generated by tools/world-gym (M2 midterm pilot)',
      Schema: 'IFC4',
    });
    const labels = family.build(creator, params);
    const result = creator.toIfc();
    return {
      seed,
      family: resolvedFamily,
      params,
      content: result.content,
      entities: result.entities,
      stats: result.stats,
      labels,
    };
  });
}

// ============================================================================
// CLI entry point
// ============================================================================

async function main() {
  const args = process.argv.slice(2);
  const getFlag = (name) => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const hasFlag = (name) => args.includes(name);

  const seedRaw = getFlag('--seed');
  if (seedRaw === undefined) {
    process.stderr.write('Usage: node generator.mjs --seed <n> [--family frame|office|auto] --out <file.ifc> [--json]\n');
    process.exit(1);
  }
  const seed = Number.isFinite(Number(seedRaw)) ? Number(seedRaw) : seedRaw;
  const family = getFlag('--family') ?? 'auto';
  const outPath = getFlag('--out');
  const jsonOutput = hasFlag('--json');

  const model = generateModel(seed, family);

  if (outPath) {
    await writeFile(outPath, model.content, 'utf-8');
  } else if (!jsonOutput) {
    process.stdout.write(model.content);
  }

  if (jsonOutput) {
    process.stdout.write(`${JSON.stringify({
      seed: model.seed,
      family: model.family,
      params: model.params,
      entityCount: model.stats.entityCount,
      fileSize: model.stats.fileSize,
      labels: model.labels,
      file: outPath ?? null,
    })}\n`);
  } else if (outPath) {
    process.stderr.write(`${model.family} seed=${model.seed}: ${model.stats.entityCount} entities, ${model.stats.fileSize} bytes -> ${outPath}\n`);
  }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    process.stderr.write(`${err.stack ?? err.message}\n`);
    process.exit(1);
  });
}
