#!/usr/bin/env node
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * World Gym procedural building generator (M2 midterm, B1.2).
 *
 * `generateModel(seed, familyName)` is the single source of truth: given a
 * seed, it deterministically picks a family (unless pinned), draws a
 * parameter set, and authors the building through the exact same
 * @ifc-lite/create code paths the CLI's `ifc-lite create` command uses -
 * metres, identity placement, one IfcCreator instance, one toIfc() call.
 *
 * Determinism: IfcCreator's first-class Timestamp + GuidSource options
 * (lib/deterministic-create.mjs) pin the header/owner-history instant and
 * every GlobalId to the seed - byte-compatible with the corpus the old
 * Date/crypto monkey-patch shim produced. Same seed in -> byte-identical
 * IFC file out, on this machine or any other.
 *
 * CLI usage:
 *   node generator.mjs --seed 42 [--family frame|office|auto] --out model.ifc [--json]
 *   node generator.mjs --seed 9 --salt-env WORLD_GYM_SALT_TEST --out model.ifc
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { IfcCreator } from '../../packages/create/dist/index.js';
import { deterministicCreateParams } from './lib/deterministic-create.mjs';
import { Rng } from './lib/rng.mjs';
import { normalizeSalt, saltFingerprint } from './lib/salt.mjs';
import {
  drawDefectPlan, applyBuildDefects, applyTextDefects, expectationsFromRecords,
} from './lib/corruption.mjs';
import * as frame from './families/frame.mjs';
import * as office from './families/office.mjs';
import { getFlag, numberFlag, seedFlag } from './lib/flags.mjs';

export const FAMILIES = { frame, office };
export const FAMILY_NAMES = Object.keys(FAMILIES);

/**
 * Generate one model for `seed`. Pure function of (seed, familyName,
 * corruption options) - no other inputs.
 *
 * Corruption (adversarial / negative-label mode): `opts.corruptRate` in
 * [0, 1] makes a per-seed Bernoulli draw on the independent `{seed}:corrupt`
 * RNG stream; `opts.forceCorrupt` (true/false) overrides the draw. A
 * corrupted model carries known-by-construction defects (see
 * lib/corruption.mjs) recorded in `model.defects` (what was planted) and
 * `model.expected` (what a correct checker must observe) - ground truth
 * that never depends on the labeler, so the labeler can be validated
 * against it. With corruptRate=0 (the default) output is byte-identical to
 * the v1 generator for every seed.
 *
 * Salt (B4.3, benchmark integrity): `opts.salt` is a secret mixed into EVERY
 * RNG stream of this function - family, params, corrupt AND the GlobalId
 * stream. Omit it (the default) and generation is byte-identical to v1 for
 * every seed; supply it and the seed alone no longer determines the model, so
 * neither the served model nor its clean twin is computable without it. The
 * salt is a per-split secret held by the scorer, not a user knob: see
 * `benchmark/splits.mjs#saltForSplit` for which split is salted (the reporting
 * split only - dev is open by design) and BENCHMARK.md sections 1a/1b for the
 * integrity model and the rotation procedure.
 *
 * @param {number|string} seed
 * @param {'frame'|'office'|'auto'} familyName
 * @param {{ corruptRate?: number, forceCorrupt?: boolean, salt?: string }} opts
 * @returns {{ seed, family, params, content, entities, stats, labels, corrupted, defects, expected }}
 */
export function generateModel(seed, familyName = 'auto', opts = {}) {
  const { corruptRate = 0, forceCorrupt } = opts;
  const salt = normalizeSalt(opts.salt);
  const pickRng = new Rng(`${seed}:family`, salt);
  const resolvedFamily = familyName === 'auto' ? pickRng.pick(FAMILY_NAMES) : familyName;
  const family = FAMILIES[resolvedFamily];
  if (!family) {
    throw new Error(`Unknown family "${familyName}". Known: ${FAMILY_NAMES.join(', ')}, auto`);
  }

  const paramRng = new Rng(`${seed}:params:${resolvedFamily}`, salt);
  const params = family.paramSpace(paramRng);

  const corruptRng = new Rng(`${seed}:corrupt`, salt);
  // Always burn the Bernoulli roll before drawing the plan, so a model
  // corrupted via --corrupt-rate is byte-identical to the same seed forced
  // with forceCorrupt: true (the plan starts at the same stream offset
  // either way) - the reward channels' determinism re-proof depends on it.
  const roll = corruptRng.float();
  const corrupted = forceCorrupt ?? (corruptRate > 0 && roll < corruptRate);
  const plan = corrupted ? drawDefectPlan(corruptRng) : [];

  const creator = new IfcCreator({
    Name: `WorldGym ${resolvedFamily} seed=${seed}`,
    Description: 'Generated by tools/world-gym (M2 midterm pilot)',
    Schema: 'IFC4',
    ...deterministicCreateParams(seed, salt),
  });
  const labels = family.build(creator, params);
  const firstStoreyId = labels.firstStoreyId;
  delete labels.firstStoreyId;
  const buildRecords = corrupted
    ? applyBuildDefects(creator, firstStoreyId, labels.footprint, plan)
    : [];
  const result = creator.toIfc();
  const model = {
    seed,
    family: resolvedFamily,
    params,
    content: result.content,
    entities: result.entities,
    stats: result.stats,
    labels,
    buildRecords,
  };

  let records = model.buildRecords;
  delete model.buildRecords;
  if (corrupted) {
    const textResult = applyTextDefects(model.content, plan);
    model.content = textResult.content;
    records = [...records, ...textResult.records];
    // Text surgery may add/remove whole STEP lines; refresh the stats the
    // label reports so they describe the bytes actually written to disk.
    model.stats = {
      ...model.stats,
      entityCount: (model.content.match(/^#\d+=/gm) ?? []).length,
      fileSize: model.content.length,
    };
  }

  model.corrupted = corrupted;
  model.defects = records;
  model.expected = expectationsFromRecords(records);
  return model;
}

// ============================================================================
// CLI entry point
// ============================================================================

/**
 * Resolve a salt from this CLI's args. Exported so any future tool that grows a
 * salt flag spells it the same way rather than inventing a second convention.
 *
 * `--salt-env VAR` is the form to prefer for anything but a local experiment: a
 * salt passed as `--salt` is visible in `ps` and in shell history, and a leaked
 * salt is a rotation event (BENCHMARK.md section 1b). The benchmark SCORER does
 * not take either flag - it reads the split's salt from the environment
 * (`splits.mjs#saltForSplit`), because which split may be salted is policy, not
 * a caller's choice.
 */
export function saltFromArgs(args, env = process.env) {
  const envVar = getFlag(args, '--salt-env');
  const literal = getFlag(args, '--salt');
  if (envVar !== undefined && literal !== undefined) {
    throw new Error('--salt and --salt-env are mutually exclusive');
  }
  if (envVar !== undefined) {
    const value = env[envVar];
    if (value === undefined) throw new Error(`--salt-env ${envVar}: environment variable is not set`);
    return normalizeSalt(value);
  }
  return normalizeSalt(literal);
}

async function main() {
  const args = process.argv.slice(2);
  const hasFlag = (name) => args.includes(name);

  if (getFlag(args, '--seed') === undefined) {
    process.stderr.write('Usage: node generator.mjs --seed <n> [--family frame|office|auto] [--corrupt | --corrupt-rate 0.3] [--salt <s> | --salt-env <VAR>] --out <file.ifc> [--json]\n');
    process.exit(1);
  }
  const seed = seedFlag(args, '--seed');
  const family = getFlag(args, '--family') ?? 'auto';
  const outPath = getFlag(args, '--out');
  const jsonOutput = hasFlag('--json');
  const forceCorrupt = hasFlag('--corrupt') ? true : undefined;
  if (forceCorrupt !== undefined && getFlag(args, '--corrupt-rate') !== undefined) {
    process.stderr.write('error: --corrupt and --corrupt-rate are mutually exclusive\n');
    process.exit(2);
  }
  const corruptRate = numberFlag(args, '--corrupt-rate', { def: 0, min: 0, max: 1 });
  const salt = saltFromArgs(args);

  const model = generateModel(seed, family, { corruptRate, forceCorrupt, salt });

  if (outPath) {
    await writeFile(outPath, model.content, 'utf-8');
  } else if (!jsonOutput) {
    process.stdout.write(model.content);
  }

  if (jsonOutput) {
    process.stdout.write(`${JSON.stringify({
      seed: model.seed,
      family: model.family,
      params: model.params,
      entityCount: model.stats.entityCount,
      fileSize: model.stats.fileSize,
      labels: model.labels,
      corrupted: model.corrupted,
      defects: model.defects,
      expected: model.expected,
      file: outPath ?? null,
      // Only present for a salted generation, so the public corpus's JSON
      // shape is untouched. It is the salt's fingerprint, never the salt.
      ...(salt ? { saltId: saltFingerprint(salt) } : {}),
    })}\n`);
  } else if (outPath) {
    process.stderr.write(`${model.family} seed=${model.seed}: ${model.stats.entityCount} entities, ${model.stats.fileSize} bytes -> ${outPath}\n`);
  }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    process.stderr.write(`${err.stack ?? err.message}\n`);
    process.exit(1);
  });
}
