// Autogenerated file: DO NOT EDIT
// Created on 7/9/2026 9:50:42 PM
#![allow(non_snake_case, non_camel_case_types, dead_code, unused_parens, unused_imports, unused_mut)]
#![allow(clippy::all)]


// ==== Intrinsics prelude (hand-written support code) ====

/// The Plato array concept: index and count.
pub trait IArray<T> {
    fn At(&self, n: i64) -> T;
    fn Count(&self) -> i64;
}

/// Vec-backed implementation of the Plato array concept.
#[derive(Clone, Debug, Default)]
pub struct Arr<T> {
    pub items: Vec<T>,
}

impl<T: Copy> Arr<T> {
    pub fn new(items: Vec<T>) -> Arr<T> { Arr { items } }
    pub fn At(&self, n: i64) -> T { self.items[n as usize] }
    pub fn Count(&self) -> i64 { self.items.len() as i64 }
    pub fn Map<U: Copy>(&self, f: impl Fn(T) -> U) -> Arr<U> {
        Arr::new(self.items.iter().map(|x| f(*x)).collect())
    }
    pub fn Reduce<TAcc>(&self, init: TAcc, f: impl Fn(TAcc, T) -> TAcc) -> TAcc {
        let mut acc = init;
        for x in &self.items {
            acc = f(acc, *x);
        }
        acc
    }
}

impl<T: Copy> IArray<T> for Arr<T> {
    fn At(&self, n: i64) -> T { Arr::At(self, n) }
    fn Count(&self) -> i64 { Arr::Count(self) }
}

pub mod Intrinsics {
    use super::*;

    pub fn MakeArray<T: Copy>(items: Vec<T>) -> Arr<T> {
        Arr::new(items)
    }

    pub fn Range(n: i64) -> Arr<i64> {
        Arr::new((0..n).collect())
    }
}

pub trait Equatable: Copy
{
    fn Equals(self, b: Self) -> bool;
}
pub trait Comparable: Copy
{
    fn Compare(self, b: Self) -> i64;
}
pub trait Numerical: Copy
{
    fn Add(self, b: Self) -> Self;
    fn Subtract(self, b: Self) -> Self;
    fn Negative(self) -> Self;
}
pub mod Constants
{
    use super::*;

    pub fn EmptyBox() -> BBox3 { BBox3::new(Vector3D::new(1E+300, 1E+300, 1E+300), Vector3D::new((1E+300).Negative(), (1E+300).Negative(), (1E+300).Negative())) }
    pub fn Pi() -> f64 { 3.141592653589793 }
    pub fn TwoPi() -> f64 { 6.283185307179586 }
}

// ==== Plato Number mapped to the native 'f64' type ====
pub trait NumberExt
{
    fn Add(self, y: f64) -> f64;
    fn Subtract(self, y: f64) -> f64;
    fn Multiply(self, y: f64) -> f64;
    fn Divide(self, y: f64) -> f64;
    fn Modulo(self, y: f64) -> f64;
    fn Negative(self) -> f64;
    fn LessThan(self, y: f64) -> bool;
    fn GreaterThan(self, y: f64) -> bool;
    fn LessThanOrEquals(self, y: f64) -> bool;
    fn GreaterThanOrEquals(self, y: f64) -> bool;
    fn Compare(self, y: f64) -> i64;
    fn Sqrt(self) -> f64;
    fn Abs(self) -> f64;
    fn Floor(self) -> f64;
    fn Pow(self, y: f64) -> f64;
    fn Acos(self) -> Angle;
    fn Asin(self) -> Angle;
    fn Atan(self) -> Angle;
    fn Square(self) -> f64;
    fn Min(self, b: f64) -> f64;
    fn Max(self, b: f64) -> f64;
    fn Clamp(self, low: f64, high: f64) -> f64;
    fn Lerp(self, b: f64, t: f64) -> f64;
    fn Turns(self) -> Angle;
    fn Degrees(self) -> Angle;
}

impl NumberExt for f64
{
    fn Add(self, y: f64) -> f64 { self + y }
    fn Subtract(self, y: f64) -> f64 { self - y }
    fn Multiply(self, y: f64) -> f64 { self * y }
    fn Divide(self, y: f64) -> f64 { self / y }
    fn Modulo(self, y: f64) -> f64 { self % y }
    fn Negative(self) -> f64 { -self }
    fn LessThan(self, y: f64) -> bool { self < y }
    fn GreaterThan(self, y: f64) -> bool { self > y }
    fn LessThanOrEquals(self, y: f64) -> bool { self <= y }
    fn GreaterThanOrEquals(self, y: f64) -> bool { self >= y }
    fn Compare(self, y: f64) -> i64 { if self < y { -1 } else if self > y { 1 } else { 0 } }
    fn Sqrt(self) -> f64 { self.sqrt() }
    fn Abs(self) -> f64 { self.abs() }
    fn Floor(self) -> f64 { self.floor() }
    fn Pow(self, y: f64) -> f64 { self.powf(y) }
    fn Acos(self) -> Angle { Angle::new(self.acos()) }
    fn Asin(self) -> Angle { Angle::new(self.asin()) }
    fn Atan(self) -> Angle { Angle::new(self.atan()) }
    fn Square(self) -> f64 { self.Multiply(self) }
    fn Min(self, b: f64) -> f64 { if self.LessThan(b) { self } else { b } }
    fn Max(self, b: f64) -> f64 { if self.LessThan(b) { b } else { self } }
    fn Clamp(self, low: f64, high: f64) -> f64 { if self.LessThan(low) { low } else { if self.GreaterThan(high) { high } else { self } } }
    fn Lerp(self, b: f64, t: f64) -> f64 { self.Multiply((1.0).Subtract(t)).Add(b.Multiply(t)) }
    fn Turns(self) -> Angle { Angle::new(self.Multiply(6.283185307179586)) }
    fn Degrees(self) -> Angle { Angle::new(self.Multiply(0.017453292519943295)) }
}
// ==== Plato Integer mapped to the native 'i64' type ====
pub trait IntegerExt
{
    fn Compare(self, y: i64) -> i64;
}

impl IntegerExt for i64
{
    fn Compare(self, y: i64) -> i64 { if self < y { -1 } else if self > y { 1 } else { 0 } }
}
// ==== Plato Boolean mapped to the native 'bool' type ====
pub trait BooleanExt
{
    fn And(self, y: bool) -> bool;
    fn Or(self, y: bool) -> bool;
    fn Not(self) -> bool;
}

impl BooleanExt for bool
{
    fn And(self, y: bool) -> bool { self && y }
    fn Or(self, y: bool) -> bool { self || y }
    fn Not(self) -> bool { !self }
}
// ==== Plato String mapped to the native 'String' type ====
// ==== Plato Character mapped to the native 'char' type ====
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct BBox3
{
    pub Min: Vector3D,
    pub Max: Vector3D,
}

impl BBox3
{
    // Constructor
    pub fn new(min: Vector3D, max: Vector3D) -> BBox3 { BBox3 { Min: min, Max: max } }

    // With functions
    pub fn WithMin(self, min: Vector3D) -> BBox3 { BBox3::new(min, self.Max) }
    pub fn WithMax(self, max: Vector3D) -> BBox3 { BBox3::new(self.Min, max) }

    // Static factory function
    pub fn Create(min: Vector3D, max: Vector3D) -> BBox3 { BBox3::new(min, max) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: BBox3) -> bool { self == other }
    pub fn NotEquals(self, other: BBox3) -> bool { self != other }

    // Implemented interface functions
    pub fn IsEmptyBox(self) -> bool { self.Max.X.LessThan(self.Min.X).Or(self.Max.Y.LessThan(self.Min.Y).Or(self.Max.Z.LessThan(self.Min.Z))) }
    pub fn Include(self, p: Vector3D) -> BBox3 { BBox3::new(self.Min.Min(p), self.Max.Max(p)) }
    pub fn Union(self, b: BBox3) -> BBox3 { BBox3::new(self.Min.Min(b.Min), self.Max.Max(b.Max)) }
    pub fn Center(self) -> Vector3D { self.Min.MidPoint(self.Max) }
    pub fn Extent(self) -> Vector3D { self.Max.Subtract(self.Min) }
    pub fn HalfDiagonal(self) -> f64 { self.Extent().Length().Multiply(0.5) }
    pub fn Contains(self, p: Vector3D) -> bool { p.X.GreaterThanOrEquals(self.Min.X).And(p.X.LessThanOrEquals(self.Max.X).And(p.Y.GreaterThanOrEquals(self.Min.Y).And(p.Y.LessThanOrEquals(self.Max.Y).And(p.Z.GreaterThanOrEquals(self.Min.Z).And(p.Z.LessThanOrEquals(self.Max.Z)))))) }
    pub fn Intersects(self, b: BBox3) -> bool { self.Min.X.LessThanOrEquals(b.Max.X).And(self.Max.X.GreaterThanOrEquals(b.Min.X).And(self.Min.Y.LessThanOrEquals(b.Max.Y).And(self.Max.Y.GreaterThanOrEquals(b.Min.Y).And(self.Min.Z.LessThanOrEquals(b.Max.Z).And(self.Max.Z.GreaterThanOrEquals(b.Min.Z)))))) }
    pub fn FoldOrigin(self, origin: Vector3D) -> BBox3 { BBox3::new(self.Min.Add(origin), self.Max.Add(origin)) }
    pub fn Expand(self, pad: f64) -> BBox3 { BBox3::new(self.Min.Subtract(Vector3D::new(pad, pad, pad)), self.Max.Add(Vector3D::new(pad, pad, pad))) }

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Error;

impl Error
{
    // Constructor
    pub fn new() -> Error { Error }

    // Static factory function
    pub fn Create() -> Error { Error::new() }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Error) -> bool { self == other }
    pub fn NotEquals(self, other: Error) -> bool { self != other }

    // Implemented interface functions

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Tuple2<T0, T1>
{
    pub X0: T0,
    pub X1: T1,
}

impl<T0: Copy + PartialEq, T1: Copy + PartialEq> Tuple2<T0, T1>
{
    // Constructor
    pub fn new(x0: T0, x1: T1) -> Tuple2<T0, T1> { Tuple2 { X0: x0, X1: x1 } }

    // With functions
    pub fn WithX0(self, x0: T0) -> Tuple2<T0, T1> { Tuple2::new(x0, self.X1) }
    pub fn WithX1(self, x1: T1) -> Tuple2<T0, T1> { Tuple2::new(self.X0, x1) }

    // Static factory function
    pub fn Create(x0: T0, x1: T1) -> Tuple2<T0, T1> { Tuple2::new(x0, x1) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Tuple2<T0, T1>) -> bool { self == other }
    pub fn NotEquals(self, other: Tuple2<T0, T1>) -> bool { self != other }

    // Implemented interface functions

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Tuple3<T0, T1, T2>
{
    pub X0: T0,
    pub X1: T1,
    pub X2: T2,
}

impl<T0: Copy + PartialEq, T1: Copy + PartialEq, T2: Copy + PartialEq> Tuple3<T0, T1, T2>
{
    // Constructor
    pub fn new(x0: T0, x1: T1, x2: T2) -> Tuple3<T0, T1, T2> { Tuple3 { X0: x0, X1: x1, X2: x2 } }

    // With functions
    pub fn WithX0(self, x0: T0) -> Tuple3<T0, T1, T2> { Tuple3::new(x0, self.X1, self.X2) }
    pub fn WithX1(self, x1: T1) -> Tuple3<T0, T1, T2> { Tuple3::new(self.X0, x1, self.X2) }
    pub fn WithX2(self, x2: T2) -> Tuple3<T0, T1, T2> { Tuple3::new(self.X0, self.X1, x2) }

    // Static factory function
    pub fn Create(x0: T0, x1: T1, x2: T2) -> Tuple3<T0, T1, T2> { Tuple3::new(x0, x1, x2) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Tuple3<T0, T1, T2>) -> bool { self == other }
    pub fn NotEquals(self, other: Tuple3<T0, T1, T2>) -> bool { self != other }

    // Implemented interface functions

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Tuple4<T0, T1, T2, T3>
{
    pub X0: T0,
    pub X1: T1,
    pub X2: T2,
    pub X3: T3,
}

impl<T0: Copy + PartialEq, T1: Copy + PartialEq, T2: Copy + PartialEq, T3: Copy + PartialEq> Tuple4<T0, T1, T2, T3>
{
    // Constructor
    pub fn new(x0: T0, x1: T1, x2: T2, x3: T3) -> Tuple4<T0, T1, T2, T3> { Tuple4 { X0: x0, X1: x1, X2: x2, X3: x3 } }

    // With functions
    pub fn WithX0(self, x0: T0) -> Tuple4<T0, T1, T2, T3> { Tuple4::new(x0, self.X1, self.X2, self.X3) }
    pub fn WithX1(self, x1: T1) -> Tuple4<T0, T1, T2, T3> { Tuple4::new(self.X0, x1, self.X2, self.X3) }
    pub fn WithX2(self, x2: T2) -> Tuple4<T0, T1, T2, T3> { Tuple4::new(self.X0, self.X1, x2, self.X3) }
    pub fn WithX3(self, x3: T3) -> Tuple4<T0, T1, T2, T3> { Tuple4::new(self.X0, self.X1, self.X2, x3) }

    // Static factory function
    pub fn Create(x0: T0, x1: T1, x2: T2, x3: T3) -> Tuple4<T0, T1, T2, T3> { Tuple4::new(x0, x1, x2, x3) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Tuple4<T0, T1, T2, T3>) -> bool { self == other }
    pub fn NotEquals(self, other: Tuple4<T0, T1, T2, T3>) -> bool { self != other }

    // Implemented interface functions

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Angle
{
    pub Radians: f64,
}

impl Angle
{
    // Constructor
    pub fn new(radians: f64) -> Angle { Angle { Radians: radians } }

    // With functions
    pub fn WithRadians(self, radians: f64) -> Angle { Angle::new(radians) }

    // Static factory function
    pub fn Create(radians: f64) -> Angle { Angle::new(radians) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Angle) -> bool { self == other }
    pub fn NotEquals(self, other: Angle) -> bool { self != other }

    // Implemented interface functions
    pub fn Cos(self) -> f64 { self.Radians.cos() }
    pub fn Sin(self) -> f64 { self.Radians.sin() }
    pub fn Tan(self) -> f64 { self.Radians.tan() }
    pub fn UnitCircle(self) -> Vector2D { Vector2D::new(self.Cos(), self.Sin()) }

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Vector2D
{
    pub X: f64,
    pub Y: f64,
}

impl Vector2D
{
    // Constructor
    pub fn new(x: f64, y: f64) -> Vector2D { Vector2D { X: x, Y: y } }

    // With functions
    pub fn WithX(self, x: f64) -> Vector2D { Vector2D::new(x, self.Y) }
    pub fn WithY(self, y: f64) -> Vector2D { Vector2D::new(self.X, y) }

    // Static factory function
    pub fn Create(x: f64, y: f64) -> Vector2D { Vector2D::new(x, y) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Vector2D) -> bool { self == other }
    pub fn NotEquals(self, other: Vector2D) -> bool { self != other }

    // Implemented interface functions
    pub fn Add(self, b: Vector2D) -> Vector2D { Vector2D::new(self.X.Add(b.X), self.Y.Add(b.Y)) }
    pub fn Subtract(self, b: Vector2D) -> Vector2D { Vector2D::new(self.X.Subtract(b.X), self.Y.Subtract(b.Y)) }
    pub fn Negative(self) -> Vector2D { Vector2D::new(self.X.Negative(), self.Y.Negative()) }
    pub fn Scale(self, s: f64) -> Vector2D { Vector2D::new(self.X.Multiply(s), self.Y.Multiply(s)) }
    pub fn Dot(self, b: Vector2D) -> f64 { self.X.Multiply(b.X).Add(self.Y.Multiply(b.Y)) }
    pub fn Cross(self, b: Vector2D) -> f64 { self.X.Multiply(b.Y).Subtract(self.Y.Multiply(b.X)) }
    pub fn LengthSquared(self) -> f64 { self.Dot(self) }
    pub fn Length(self) -> f64 { self.LengthSquared().Sqrt() }
    pub fn Normalize(self) -> Vector2D { self.Scale((1.0).Divide(self.Length())) }
    pub fn Distance(self, b: Vector2D) -> f64 { b.Subtract(self).Length() }
    pub fn DistanceSquared(self, b: Vector2D) -> f64 { b.Subtract(self).LengthSquared() }
    pub fn Lerp(self, b: Vector2D, t: f64) -> Vector2D { self.Scale((1.0).Subtract(t)).Add(b.Scale(t)) }
    pub fn MidPoint(self, b: Vector2D) -> Vector2D { self.Add(b).Scale(0.5) }

    // Unimplemented interface functions
}
#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub struct Vector3D
{
    pub X: f64,
    pub Y: f64,
    pub Z: f64,
}

impl Vector3D
{
    // Constructor
    pub fn new(x: f64, y: f64, z: f64) -> Vector3D { Vector3D { X: x, Y: y, Z: z } }

    // With functions
    pub fn WithX(self, x: f64) -> Vector3D { Vector3D::new(x, self.Y, self.Z) }
    pub fn WithY(self, y: f64) -> Vector3D { Vector3D::new(self.X, y, self.Z) }
    pub fn WithZ(self, z: f64) -> Vector3D { Vector3D::new(self.X, self.Y, z) }

    // Static factory function
    pub fn Create(x: f64, y: f64, z: f64) -> Vector3D { Vector3D::new(x, y, z) }

    // Equality (via PartialEq)
    pub fn Equals(self, other: Vector3D) -> bool { self == other }
    pub fn NotEquals(self, other: Vector3D) -> bool { self != other }

    // Implemented interface functions
    pub fn Add(self, b: Vector3D) -> Vector3D { Vector3D::new(self.X.Add(b.X), self.Y.Add(b.Y), self.Z.Add(b.Z)) }
    pub fn Subtract(self, b: Vector3D) -> Vector3D { Vector3D::new(self.X.Subtract(b.X), self.Y.Subtract(b.Y), self.Z.Subtract(b.Z)) }
    pub fn Negative(self) -> Vector3D { Vector3D::new(self.X.Negative(), self.Y.Negative(), self.Z.Negative()) }
    pub fn Scale(self, s: f64) -> Vector3D { Vector3D::new(self.X.Multiply(s), self.Y.Multiply(s), self.Z.Multiply(s)) }
    pub fn Dot(self, b: Vector3D) -> f64 { self.X.Multiply(b.X).Add(self.Y.Multiply(b.Y).Add(self.Z.Multiply(b.Z))) }
    pub fn Cross(self, b: Vector3D) -> Vector3D { Vector3D::new(self.Y.Multiply(b.Z).Subtract(self.Z.Multiply(b.Y)), self.Z.Multiply(b.X).Subtract(self.X.Multiply(b.Z)), self.X.Multiply(b.Y).Subtract(self.Y.Multiply(b.X))) }
    pub fn LengthSquared(self) -> f64 { self.Dot(self) }
    pub fn Length(self) -> f64 { self.LengthSquared().Sqrt() }
    pub fn Normalize(self) -> Vector3D { self.Scale((1.0).Divide(self.Length())) }
    pub fn Distance(self, b: Vector3D) -> f64 { b.Subtract(self).Length() }
    pub fn DistanceSquared(self, b: Vector3D) -> f64 { b.Subtract(self).LengthSquared() }
    pub fn Lerp(self, b: Vector3D, t: f64) -> Vector3D { self.Scale((1.0).Subtract(t)).Add(b.Scale(t)) }
    pub fn MidPoint(self, b: Vector3D) -> Vector3D { self.Add(b).Scale(0.5) }
    pub fn Min(self, b: Vector3D) -> Vector3D { Vector3D::new(self.X.Min(b.X), self.Y.Min(b.Y), self.Z.Min(b.Z)) }
    pub fn Max(self, b: Vector3D) -> Vector3D { Vector3D::new(self.X.Max(b.X), self.Y.Max(b.Y), self.Z.Max(b.Z)) }
    pub fn MaxComponent(self) -> f64 { self.X.Max(self.Y).Max(self.Z) }
    pub fn Perpendicular(self) -> Vector3D { (if self.X.Abs().LessThan(0.9) { self.Cross(Vector3D::new(1.0, 0.0, 0.0)) } else { self.Cross(Vector3D::new(0.0, 1.0, 0.0)) }).Normalize() }
    pub fn Reflect(self, normal: Vector3D) -> Vector3D { self.Subtract(normal.Scale((2.0).Multiply(self.Dot(normal)))) }

    // Unimplemented interface functions
}
