/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * The corpus cases ifc-lite proposes upstream (IDS-126), generated by
 * `scripts/ids-conformance/proposed-cases.mjs` into
 * `docs/architecture/ids-studio/upstream/proposed-corpus-cases/`. Each is
 * routed like a corpus case (`pass-`/`fail-` to the validator, `invalid-` to
 * the audit) and must get the verdict in its name, so a proposal never
 * claims a verdict our own engine does not give. Folders starting `ids11-`
 * are IDS 1.1 candidates and run with the preview. Each `.ids` must also be
 * exactly what the writer produces for its own parse (generated, not
 * hand-edited).
 */

import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { IfcParser } from '@ifc-lite/parser';
import { parseIDS } from '../parser/xml-parser.js';
import { writeIdsXml } from '../writer/index.js';
import { validateIDS } from '../validation/validator.js';
import { auditIDSDocument } from '../audit/index.js';
import { createDataAccessor } from '../bridge/index.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../../../docs/architecture/ids-studio/upstream/proposed-corpus-cases');

const CASES = readdirSync(ROOT).sort().flatMap((group) =>
  readdirSync(join(ROOT, group)).filter((f) => f.endsWith('.ids')).sort().map((file) => ({
    id: `${group}/${file.slice(0, -4)}`,
    expected: file.split('-')[0] as 'pass' | 'fail' | 'invalid',
    options: group.startsWith('ids11-') ? { preview: { ids11: true } } : {},
    ids: readFileSync(join(ROOT, group, file), 'utf8'),
    ifcPath: join(ROOT, group, `${file.slice(0, -4)}.ifc`),
  })));

describe('proposed upstream corpus cases', () => {
  it('finds the generated cases', () => {
    expect(CASES.length).toBe(7);
  });

  for (const c of CASES) {
    it(`${c.id} is written by the writer`, () => {
      expect(writeIdsXml(parseIDS(c.ids, c.options), {}, c.options)).toBe(c.ids);
    });

    it(`${c.id} -> ${c.expected}`, async () => {
      if (c.expected === 'invalid') {
        const report = await auditIDSDocument(c.ids, c.options);
        expect(report.issues.filter((i) => i.severity === 'error').length).toBeGreaterThan(0);
        return;
      }
      expect((await auditIDSDocument(c.ids, c.options)).issues.filter((i) => i.severity === 'error')).toEqual([]);
      const bytes = readFileSync(c.ifcPath);
      const store = await new IfcParser().parseColumnar(
        bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer,
      );
      const report = await validateIDS(parseIDS(c.ids, c.options), createDataAccessor(store), {
        modelId: c.id, schemaVersion: String(store.schemaVersion ?? 'IFC4'), entityCount: 0,
      }, c.options);
      expect(report.specificationResults.map((r) => r.status)).toEqual([c.expected]);
    });
  }
});
